name: ✨Feature
description: Add a new feature
title: 'feat: '
labels: ['feature']

body:
  - type: textarea
    id: description
    attributes:
      label: Feature description
      placeholder: 'What will be added and why is it important?'
    validations:
      required: true
