name: ✨ Feature request
description: 'Propose a new feature (commit type: feat)'
title: "feat(scope): short description"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request

        Commit type: **feat**

  - type: input
    id: scope
    attributes:
      label: Scope
      placeholder: auth / dashboard / api
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
