name: ♻️ Refactor
description: 'Code refactoring (commit type: refactor)'
title: 'refactor(scope): short description'
labels: ['refactor']
body:
  - type: input
    id: scope
    attributes:
      label: Scope
      placeholder: core / api / ui
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Reason
      description: Why is this refactor needed?
    validations:
      required: true
